---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
  vars:
    zulu_version: 11
    zulu_release: 11.39.15
    zulu_jdk_version: jdk11.0.7
    java_home: /usr/lib/jvm/zulu-{{ zulu_version }}
    
  roles:
    - role: jeduoliveira.zulu_openjdk
    - role: jeduoliveira.tomcat
